package javaSandy;

/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTAdd extends SimpleNode {
	public ASTAdd(int id) {
		super(id);
	}

	public ASTAdd(Prog2 p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=28691e030ce06f9fea8f695a564c357b (do not edit this
 * line)
 */
