package javaSandy;

/* Generated By:JJTree: Do not edit this line. ASTdiv.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTdiv extends SimpleNode {
	public ASTdiv(int id) {
		super(id);
	}

	public ASTdiv(Prog2 p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=ca8b130e5a6dd91746a6b6076ac7bad7 (do not edit this
 * line)
 */
