package javaSandy;

/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTInteger extends SimpleNode {
	public ASTInteger(int id) {
		super(id);
	}

	public ASTInteger(P2 p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=464e01512e91932f3cb0722992c659cf (do not edit this
 * line)
 */
