package javaSandy;

/* Generated By:JJTree: Do not edit this line. ASTLAMBDA.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTLAMBDA extends SimpleNode {
	public ASTLAMBDA(int id) {
		super(id);
	}

	public ASTLAMBDA(Prog2 p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=1d501e4b913d60695d37aeb0f6561648 (do not edit this
 * line)
 */
