package javaSandy;

/* Generated By:JJTree: Do not edit this line. ASTMult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMult extends SimpleNode {
	public ASTMult(int id) {
		super(id);
	}

	public ASTMult(P2 p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=aebbd1e21b0c0505122dada3321a8211 (do not edit this
 * line)
 */
