package javaSandy;

/* Generated By:JJTree: Do not edit this line. ASTMyID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMyID extends SimpleNode {
	private String name;

	public void setName(String n) {
		name = n;
	}

	public String toString() {
		return "Identifier: " + name;
	}

	public ASTMyID(int id) {
		super(id);
	}

	public ASTMyID(Prog2 p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=cfff7edb50aad1b265b451837a0c834a (do not edit this
 * line)
 */
