package javaSandy;

/* Generated By:JJTree: Do not edit this line. ASTMyID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMyID extends SimpleNode {
	private String name;

	public ASTMyID(int id) {
		super(id);
	}

	public ASTMyID(eg2 p, int id) {
		super(p, id);
	}

	public void setName(String n) {
		name = n;
	}

	public String toString() {
		return "Identifier: " + name;
	}
}
/*
 * JavaCC - OriginalChecksum=ccf1e6e1b8578c98f15c4896cb3f8a64 (do not edit this
 * line)
 */
