package javaSandy;
/* Generated By:JJTree: Do not edit this line. ASTmod.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmod extends SimpleNode {
  public ASTmod(int id) {
    super(id);
  }

  public ASTmod(Prog2 p, int id) {
    super(p, id);
  }

  /* Added method */

  public void printExpr() {
    System.out.print("%");
  }

}
/* JavaCC - OriginalChecksum=c63839db3707cb7090926dfcfd8854a8 (do not edit this line) */
