package javaSandy;

/* Generated By:JJTree: Do not edit this line. ASTStart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTStart extends SimpleNode {
	public ASTStart(int id) {
		super(id);
	}

	public ASTStart(P2 p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=b3c0f50c9146708f544c76d47209abc1 (do not edit this
 * line)
 */
