package javaSandy;

/* Generated By:JJTree: Do not edit this line. ASTsub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTsub extends SimpleNode {
	public ASTsub(int id) {
		super(id);
	}

	public ASTsub(Prog2 p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=52c3662118d5fec761a593cd889bed98 (do not edit this
 * line)
 */
