package javaSandy;

/* Generated By:JavaCC: Do not edit this line. eg2TreeConstants.java Version 5.0 */
public interface eg2TreeConstants {
	public int JJTSTART = 0;
	public int JJTVOID = 1;
	public int JJTADD = 2;
	public int JJTMULT = 3;
	public int JJTMYID = 4;
	public int JJTINTEGER = 5;

	public String[] jjtNodeName = { "Start", "void", "Add", "Mult", "MyID", "Integer", };
}
/*
 * JavaCC - OriginalChecksum=cb8cbf3c16ca4ae9d060cac20c45ea74 (do not edit this
 * line)
 */
