package javaSandy;

/* Generated By:JavaCC: Do not edit this line. P2TreeConstants.java Version 5.0 */
public interface P2TreeConstants {
	public int JJTSTART = 0;
	public int JJTVOID = 1;
	public int JJTADD = 2;
	public int JJTMULT = 3;
	public int JJTMYID = 4;
	public int JJTINTEGER = 5;

	public String[] jjtNodeName = { "Start", "void", "Add", "Mult", "MyID", "Integer", };
}
/*
 * JavaCC - OriginalChecksum=6cf9a8dd6a3903ba25b656dfad4d821b (do not edit this
 * line)
 */
