package javaSandy;

/* Generated By:JavaCC: Do not edit this line. Prog2TreeConstants.java Version 5.0 */
public interface Prog2TreeConstants {
	public int JJTSTART = 0;
	public int JJTVOID = 1;
	public int JJTADD = 2;
	public int JJTMULT = 3;
	public int JJTMYID = 4;
	public int JJTINTEGER = 5;

	public String[] jjtNodeName = { "Start", "void", "Add", "Mult", "MyID", "Integer", };
}
/*
 * JavaCC - OriginalChecksum=81515f9cdce7fb4e6dde97ac70adb93d (do not edit this
 * line)
 */
