package javaSandy;

/* Generated By:JavaCC: Do not edit this line. Prog2TreeConstants.java Version 5.0 */
public interface Prog2TreeConstants {
	public int JJTSTART = 0;
	public int JJTVOID = 1;
	public int JJTADD = 2;
	public int JJTSUB = 3;
	public int JJTMUL = 4;
	public int JJTDIV = 5;
	public int JJTLAMBDA = 6;
	public int JJTMYID = 7;

	public String[] jjtNodeName = { "Start", "void", "add", "sub", "mul", "div", "LAMBDA", "MyID", };
}
/*
 * JavaCC - OriginalChecksum=4b2ae59e0e088f675ec99da0d30a26c6 (do not edit this
 * line)
 */
