package javaSandy;
/* Generated By:JavaCC: Do not edit this line. Prog2TreeConstants.java Version 5.0 */
public interface Prog2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTMUL = 4;
  public int JJTDIV = 5;
  public int JJTMOD = 6;
  public int JJTVAR = 7;
  public int JJTNUM = 8;
  public int JJTAPPL = 9;
  public int JJTLAMB = 10;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "add",
    "sub",
    "mul",
    "div",
    "mod",
    "var",
    "num",
    "appl",
    "lamb",
  };
}
/* JavaCC - OriginalChecksum=a14cd5dfa6a755ce91f7e521cfa06ae5 (do not edit this line) */
