package javaSandy;

import java.util.Scanner;

/* Generated By:JJTree&JavaCC: Do not edit this line. Prog2.java */
class Prog2/*@bgen(jjtree)*/implements Prog2TreeConstants, Prog2Constants {/*@bgen(jjtree)*/
  protected JJTProg2State jjtree = new JJTProg2State();
  
  public static void main(String args[]) {
	  System.out.println("Enter an applied Lambda expression:");
	    Prog2 t = new Prog2(System.in);
	    try {
	      ASTStart n = t.Start();
	      SimpleNode expr = (SimpleNode)n.jjtGetChild(0);

	      // Print the abstract syntax tree
	      System.out.println();
	      System.out.println("The abstract syntax tree:");
	      expr.dump("");
	      System.out.println();
	      
	      System.out.println("Enter the variable to be substituted:");
	      Scanner sc = new Scanner(System.in); 
	      String sVarToSubstitute = sc.next();
	      System.out.println();
	      
	      System.out.println("Enter the substituting applied Lambda expression:");
	      //Prog2.ReInit(System.in);
	      Prog2 t2 = new Prog2(System.in);
	      ASTStart n2 = t2.Start();
	      SimpleNode expr1 = (SimpleNode)n2.jjtGetChild(0);
	      
	      // Print the abstract syntax tree
	      System.out.println();
	      System.out.println("The abstract syntax tree:");
	      expr1.dump("");
	      
	      // Print the abstract syntax tree substitution result 
	      System.out.println();
	      System.out.println("The substitution result:");
	      expr1.substitute();
	      expr1.dump("");
	      System.out.println();
	
	      System.out.println(">>> Lambda Expression Evaluator <<<");
	      System.out.println("Enter an applied Lambda expression:");
	      Prog2 t3 = new Prog2(System.in);
	      
	      ASTStart n3 = t3.Start();
	      SimpleNode expr2 = (SimpleNode)n3.jjtGetChild(0);
	      System.out.println();
	      System.out.println("The applicative order evaluation result:");
	      expr2.applicativeOrderEvaluate();
	      
	} catch (Exception e) {
    System.out.println("Oops.");
    System.out.println(e.getMessage());
    e.printStackTrace();
  }
}

  final public ASTStart Start() throws ParseException {
                    /*@bgen(jjtree) Start */
  ASTStart jjtn000 = new ASTStart(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      Expression();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public void Expression() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      Identifier();
      break;
    case NUMBER:
      Number();
      break;
    case 12:
               ASTadd jjtn001 = new ASTadd(JJTADD);
               boolean jjtc001 = true;
               jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(12);
      } finally {
               if (jjtc001) {
                 jjtree.closeNodeScope(jjtn001,  0);
               }
      }
      break;
    case 13:
                             ASTsub jjtn002 = new ASTsub(JJTSUB);
                             boolean jjtc002 = true;
                             jjtree.openNodeScope(jjtn002);
      try {
        jj_consume_token(13);
      } finally {
                             if (jjtc002) {
                               jjtree.closeNodeScope(jjtn002,  0);
                             }
      }
      break;
    case 14:
                                           ASTmul jjtn003 = new ASTmul(JJTMUL);
                                           boolean jjtc003 = true;
                                           jjtree.openNodeScope(jjtn003);
      try {
        jj_consume_token(14);
      } finally {
                                           if (jjtc003) {
                                             jjtree.closeNodeScope(jjtn003,  0);
                                           }
      }
      break;
    case 15:
                                                         ASTdiv jjtn004 = new ASTdiv(JJTDIV);
                                                         boolean jjtc004 = true;
                                                         jjtree.openNodeScope(jjtn004);
      try {
        jj_consume_token(15);
      } finally {
                                                         if (jjtc004) {
                                                           jjtree.closeNodeScope(jjtn004,  0);
                                                         }
      }
      break;
    case 16:
                                                                       ASTmod jjtn005 = new ASTmod(JJTMOD);
                                                                       boolean jjtc005 = true;
                                                                       jjtree.openNodeScope(jjtn005);
      try {
        jj_consume_token(16);
      } finally {
                                                                       if (jjtc005) {
                                                                         jjtree.closeNodeScope(jjtn005,  0);
                                                                       }
      }
      break;
    case 17:
      jj_consume_token(17);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUMBER:
      case IDENTIFIER:
      case 12:
      case 13:
      case 14:
      case 15:
      case 16:
      case 17:
        Application();
        break;
      case LAMBDA:
        Abstraction();
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(18);
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void Identifier() throws ParseException {
 /*@bgen(jjtree) var */
  ASTvar jjtn000 = new ASTvar(JJTVAR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(IDENTIFIER);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    jjtn000.setName(t.image);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void Number() throws ParseException {
 /*@bgen(jjtree) num */
  ASTnum jjtn000 = new ASTnum(JJTNUM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(NUMBER);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    jjtn000.setValue(t.image);
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void Application() throws ParseException {
    Expression();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NUMBER:
      case IDENTIFIER:
      case 12:
      case 13:
      case 14:
      case 15:
      case 16:
      case 17:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_1;
      }
                   ASTappl jjtn001 = new ASTappl(JJTAPPL);
                   boolean jjtc001 = true;
                   jjtree.openNodeScope(jjtn001);
      try {
        Expression();
      } catch (Throwable jjte001) {
                   if (jjtc001) {
                     jjtree.clearNodeScope(jjtn001);
                     jjtc001 = false;
                   } else {
                     jjtree.popNode();
                   }
                   if (jjte001 instanceof RuntimeException) {
                     {if (true) throw (RuntimeException)jjte001;}
                   }
                   if (jjte001 instanceof ParseException) {
                     {if (true) throw (ParseException)jjte001;}
                   }
                   {if (true) throw (Error)jjte001;}
      } finally {
                   if (jjtc001) {
                     jjtree.closeNodeScope(jjtn001,  2);
                   }
      }
    }
  }

  final public void Abstraction() throws ParseException {
    jj_consume_token(LAMBDA);
    Identifier();
                          ASTlamb jjtn001 = new ASTlamb(JJTLAMB);
                          boolean jjtc001 = true;
                          jjtree.openNodeScope(jjtn001);
    try {
      Body();
    } catch (Throwable jjte001) {
                          if (jjtc001) {
                            jjtree.clearNodeScope(jjtn001);
                            jjtc001 = false;
                          } else {
                            jjtree.popNode();
                          }
                          if (jjte001 instanceof RuntimeException) {
                            {if (true) throw (RuntimeException)jjte001;}
                          }
                          if (jjte001 instanceof ParseException) {
                            {if (true) throw (ParseException)jjte001;}
                          }
                          {if (true) throw (Error)jjte001;}
    } finally {
                          if (jjtc001) {
                            jjtree.closeNodeScope(jjtn001,  2);
                          }
    }
  }

  final public void Body() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      Identifier();
                 ASTlamb jjtn001 = new ASTlamb(JJTLAMB);
                 boolean jjtc001 = true;
                 jjtree.openNodeScope(jjtn001);
      try {
        Body();
      } catch (Throwable jjte001) {
                 if (jjtc001) {
                   jjtree.clearNodeScope(jjtn001);
                   jjtc001 = false;
                 } else {
                   jjtree.popNode();
                 }
                 if (jjte001 instanceof RuntimeException) {
                   {if (true) throw (RuntimeException)jjte001;}
                 }
                 if (jjte001 instanceof ParseException) {
                   {if (true) throw (ParseException)jjte001;}
                 }
                 {if (true) throw (Error)jjte001;}
      } finally {
                 if (jjtc001) {
                   jjtree.closeNodeScope(jjtn001,  2);
                 }
      }
      break;
    case 19:
      jj_consume_token(19);
      Application();
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  /** Generated Token Manager. */
  public Prog2TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[4];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x3f380,0x3f300,0x3f300,0x80200,};
   }

  /** Constructor with InputStream. */
  public Prog2(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Prog2(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new Prog2TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Prog2(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new Prog2TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Prog2(Prog2TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(Prog2TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 4; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[20];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 4; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 20; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
